# Generated by Django 5.1 on 2024-08-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_newsletter_options_newsletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], max_length=10),
        ),
    ]
